# Generated by Django 6.0.5 on 2026-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispensed', 'Dispensed')], default='Pending', max_length=20),
        ),
    ]
