# Generated by Django 6.0.5 on 2026-05-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_bill_prescription_bill_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('pharmacy', 'Pharmacy')], default='appointment', max_length=20),
        ),
    ]
