# Generated by Django 6.0.3 on 2026-05-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_bill_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('ward_type', models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Semi Private', 'Semi Private'), ('Private Room', 'Private Room')], max_length=50)),
                ('bed_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Ready For Discharge', 'Ready For Discharge'), ('Discharged', 'Discharged'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
            ],
            options={
                'db_table': 'admissions',
            },
        ),
        migrations.CreateModel(
            name='Casuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('emergency_reason', models.TextField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Under Treatment', 'Under Treatment'), ('Shifted to Ward', 'Shifted to Ward'), ('Discharged', 'Discharged')], default='Waiting', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
            ],
            options={
                'db_table': 'casuality',
            },
        ),
        migrations.CreateModel(
            name='IPBill',
            fields=[
                ('ip_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(db_column='admission_id', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.admission')),
            ],
            options={
                'db_table': 'ip_bills',
            },
        ),
        migrations.CreateModel(
            name='IPCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('Room Charge', 'Room Charge'), ('Doctor Visit', 'Doctor Visit'), ('Nursing Charge', 'Nursing Charge'), ('Procedure Charge', 'Procedure Charge'), ('Pharmacy Bill', 'Pharmacy Bill'), ('Emergency Charge', 'Emergency Charge')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='hospitalapp.admission')),
                ('pharmacy_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ip_charges', to='hospitalapp.bill')),
            ],
            options={
                'db_table': 'ip_charges',
            },
        ),
    ]
