# Generated by Django 6.0.3 on 2026-05-26 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_admission_casuality_ipbill_ipcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20, unique=True)),
                ('ward_type', models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Semi Private', 'Semi Private'), ('Private Room', 'Private Room')], max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_beds', to='hospitalapp.patient')),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['ward_type', 'bed_number'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospitalapp.bed'),
        ),
    ]
