# Generated by Django 6.0.3 on 2026-05-26 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_bed_admission_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ambulances',
            },
        ),
        migrations.CreateModel(
            name='LaundryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('Bedsheet', 'Bedsheet'), ('Uniform', 'Uniform'), ('Patient Clothes', 'Patient Clothes')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Washing', 'Washing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laundry_logs',
            },
        ),
        migrations.CreateModel(
            name='NonStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Laundry', 'Laundry'), ('Security', 'Security'), ('Maintenance', 'Maintenance')], max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duty_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Off-duty', 'Off-duty')], default='Available', max_length=20)),
            ],
            options={
                'db_table': 'non_staff',
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_incidents',
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitor_logs',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('receptionist', 'receptionist'), ('pharmacist', 'pharmacist'), ('patient', 'patient'), ('nurse', 'nurse')], max_length=20),
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caller_name', models.CharField(max_length=100)),
                ('caller_phone', models.CharField(max_length=15)),
                ('pickup_location', models.CharField(max_length=255)),
                ('emergency_priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.ambulance')),
            ],
            options={
                'db_table': 'ambulance_requests',
            },
        ),
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleaner', models.ForeignKey(limit_choices_to={'role': 'Cleaning'}, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nonstaff')),
            ],
            options={
                'db_table': 'cleaning_logs',
            },
        ),
        migrations.CreateModel(
            name='NonStaffShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Off', 'Off')], default='Present', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hospitalapp.nonstaff')),
            ],
            options={
                'db_table': 'non_staff_shifts',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('assigned_ward', models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Semi Private', 'Semi Private'), ('Private Room', 'Private Room')], max_length=50)),
                ('is_head_nurse', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nurses',
            },
        ),
        migrations.CreateModel(
            name='MedicineAdministration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=50)),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_medicines', to='hospitalapp.admission')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'medicine_administrations',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='hospitalapp.admission')),
                ('triggered_by_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'emergency_alerts',
            },
        ),
        migrations.CreateModel(
            name='NurseNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='hospitalapp.admission')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'nurse_notes',
            },
        ),
        migrations.CreateModel(
            name='NursePatientAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_assignments', to='hospitalapp.admission')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'nurse_patient_assignments',
            },
        ),
        migrations.CreateModel(
            name='NurseShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Off', 'Off')], default='Present', max_length=20)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'nurse_shifts',
            },
        ),
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('oxygen_level', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('sugar_level', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField()),
                ('patient_condition', models.CharField(choices=[('Stable', 'Stable'), ('Observation', 'Observation'), ('Serious', 'Serious'), ('Critical', 'Critical')], default='Stable', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospitalapp.admission')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'vital_records',
            },
        ),
    ]
