# Generated by Django 6.0.3 on 2026-05-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_ambulance_laundrylog_nonstaff_securityincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineadministration',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='hospitalapp.medicine'),
        ),
        migrations.AddField(
            model_name='medicineadministration',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='InpatientPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_prescriptions', to='hospitalapp.admission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'inpatient_prescriptions',
            },
        ),
        migrations.CreateModel(
            name='InpatientPrescriptionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('route', models.CharField(choices=[('Tablet', 'Tablet'), ('Injection', 'Injection'), ('IV', 'IV'), ('Syrup', 'Syrup'), ('Drops', 'Drops'), ('Nebulization', 'Nebulization')], max_length=30)),
                ('duration_days', models.IntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospitalapp.inpatientprescription')),
            ],
            options={
                'db_table': 'inpatient_prescription_items',
            },
        ),
        migrations.CreateModel(
            name='MedicationScheduleEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Administered', 'Administered'), ('Missed', 'Missed'), ('Delayed', 'Delayed'), ('Refused', 'Refused')], default='Pending', max_length=20)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.nurse')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='hospitalapp.admission')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='hospitalapp.inpatientprescriptionitem')),
            ],
            options={
                'db_table': 'medication_schedule_entries',
            },
        ),
        migrations.AddField(
            model_name='medicineadministration',
            name='schedule_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='hospitalapp.medicationscheduleentry'),
        ),
    ]
