# Generated by Django 6.0.3 on 2026-05-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_medicineadministration_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casuality',
            name='referred_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_referrals', to='hospitalapp.doctor'),
        ),
        migrations.AlterField(
            model_name='casuality',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Emergency Care', 'Under Emergency Care'), ('Stabilized', 'Stabilized'), ('Referred', 'Referred'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Pending', max_length=30),
        ),
    ]
