# Generated by Django 6.0.3 on 2026-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_casuality_referred_doctor_alter_casuality_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='ward_type',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Semi Private', 'Semi Private'), ('Private Room', 'Private Room'), ('Casuality Ward', 'Casuality Ward')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bed',
            name='ward_type',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Semi Private', 'Semi Private'), ('Private Room', 'Private Room'), ('Casuality Ward', 'Casuality Ward')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='assigned_ward',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Semi Private', 'Semi Private'), ('Private Room', 'Private Room'), ('Casuality Ward', 'Casuality Ward')], max_length=50),
        ),
    ]
