# Generated by Django 6.0.5 on 2026-05-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_alter_admission_ward_type_alter_bed_ward_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casuality',
            name='referred_doctor',
        ),
        migrations.CreateModel(
            name='AdmissionConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='hospitalapp.admission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'admission_consultants',
            },
        ),
        migrations.CreateModel(
            name='CasualityReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('casualty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='hospitalapp.casuality')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='hospitalapp.doctor')),
                ('referred_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'casuality_referrals',
            },
        ),
        migrations.CreateModel(
            name='EmergencyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('casualty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_prescriptions', to='hospitalapp.casuality')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyPrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospitalapp.emergencyprescription')),
            ],
        ),
    ]
