# Generated by Django 6.0.3 on 2026-05-29 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0014_remove_casuality_referred_doctor_admissionconsultant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualityreferral',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='hospitalapp.admission')),
                ('casualty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='hospitalapp.casuality')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investigation_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Suggested', 'Suggested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Suggested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='hospitalapp.admission')),
                ('casualty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='hospitalapp.casuality')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'investigation_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
