# Generated by Django 6.0.3 on 2026-05-29 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0015_casualityreferral_notes_clinicalnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineadministration',
            name='casualty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_medicines', to='hospitalapp.casuality'),
        ),
        migrations.AddField(
            model_name='nursenote',
            name='casualty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='hospitalapp.casuality'),
        ),
        migrations.AddField(
            model_name='vitalrecord',
            name='casualty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospitalapp.casuality'),
        ),
        migrations.AlterField(
            model_name='medicineadministration',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_medicines', to='hospitalapp.admission'),
        ),
        migrations.AlterField(
            model_name='nursenote',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='hospitalapp.admission'),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospitalapp.admission'),
        ),
    ]
