# Generated by Django 6.0.3 on 2026-05-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0016_medicineadministration_casualty_nursenote_casualty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyprescriptionitem',
            name='administered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyprescriptionitem',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_administrations', to='hospitalapp.nurse'),
        ),
        migrations.AddField(
            model_name='emergencyprescriptionitem',
            name='is_administered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineadministration',
            name='emergency_prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='hospitalapp.emergencyprescriptionitem'),
        ),
    ]
