# Generated by Django 6.0.3 on 2026-05-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0017_emergencyprescriptionitem_administered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualtyBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('Medicine', 'Medicine'), ('Procedure', 'Procedure'), ('Consultation', 'Consultation'), ('Investigation', 'Investigation'), ('Other', 'Other')], default='Medicine', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.nurse')),
                ('casualty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_bills', to='hospitalapp.casuality')),
                ('emergency_prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_entries', to='hospitalapp.emergencyprescriptionitem')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casualty_charges', to='hospitalapp.medicine')),
            ],
            options={
                'db_table': 'casualty_bills',
                'ordering': ['-created_at'],
            },
        ),
    ]
