# Generated by Django 6.0.3 on 2026-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0018_add_casualty_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualtybill',
            name='merged_to_ip',
            field=models.BooleanField(default=False),
        ),
    ]
