# Generated by Django 6.0.3 on 2026-06-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0019_casualtybill_merged_to_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='admission',
            field=models.ForeignKey(blank=True, db_column='admission_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_prescriptions', to='hospitalapp.admission'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
