# Generated by Django 6.0.3 on 2026-06-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0021_labtest_radiologytest_alter_user_role_laborder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.appointment'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology')], default='appointment', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipcharge',
            name='charge_type',
            field=models.CharField(choices=[('Room Charge', 'Room Charge'), ('Doctor Visit', 'Doctor Visit'), ('Nursing Charge', 'Nursing Charge'), ('Procedure Charge', 'Procedure Charge'), ('Pharmacy Bill', 'Pharmacy Bill'), ('Emergency Charge', 'Emergency Charge'), ('Laboratory Charge', 'Laboratory Charge'), ('Radiology Charge', 'Radiology Charge')], max_length=50),
        ),
    ]
