# Generated by Django 6.0.3 on 2026-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0022_alter_bill_appointment_alter_bill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('receptionist', 'receptionist'), ('pharmacist', 'pharmacist'), ('patient', 'patient'), ('nurse', 'nurse'), ('lab_technician', 'Lab Technician'), ('laboratoryist', 'Laboratoryist'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist')], max_length=20),
        ),
    ]
