# Generated by Django 6.0.3 on 2026-06-03 05:03
# Modified: Removed AddField operations for columns that already exist in the DB.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0023_alter_user_role'),
    ]

    operations = [
        # ----------------------------------------------------------------
        # AlterField: update STATUS choices on existing tables
        # ----------------------------------------------------------------
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Collected', 'Collected'),
                    ('Processing', 'Processing'),
                    ('Result Entered', 'Result Entered'),
                    ('Completed', 'Completed'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='radiologyorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Scheduled', 'Scheduled'),
                    ('Arrived', 'Arrived'),
                    ('Scanning', 'Scanning'),
                    ('Scanned', 'Scanned'),
                    ('Completed', 'Completed'),
                    ('Reported', 'Reported'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
        # ----------------------------------------------------------------
        # AlterModelTable: rename radiologyreport table to radiology_reports
        # ----------------------------------------------------------------
        migrations.AlterModelTable(
            name='radiologyreport',
            table='radiology_reports',
        ),
        # ----------------------------------------------------------------
        # CreateModel: new tables only
        # ----------------------------------------------------------------
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='DoctorNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(
                    choices=[
                        ('Lab Report', 'Lab Report'),
                        ('Radiology Report', 'Radiology Report'),
                        ('Critical Lab Result', 'Critical Lab Result'),
                        ('Critical Radiology Finding', 'Critical Radiology Finding'),
                    ],
                    max_length=50,
                )),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'doctor_notifications',
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_type', models.CharField(
                    choices=[
                        ('Blood', 'Blood'),
                        ('Urine', 'Urine'),
                        ('Stool', 'Stool'),
                        ('Sputum', 'Sputum'),
                        ('Swab', 'Swab'),
                        ('Tissue Sample', 'Tissue Sample'),
                    ],
                    max_length=50,
                )),
                ('collection_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='hospitalapp.laborder')),
            ],
            options={
                'db_table': 'lab_samples',
            },
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('male_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('male_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('female_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('female_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('critical_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('critical_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='hospitalapp.labtest')),
            ],
            options={
                'db_table': 'lab_test_parameters',
            },
        ),
        migrations.CreateModel(
            name='LabParameterResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_results', to='hospitalapp.labresult')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.labtestparameter')),
            ],
            options={
                'db_table': 'lab_parameter_results',
            },
        ),
        migrations.CreateModel(
            name='RadiologyAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='radiology_scans/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hospitalapp.radiologyorder')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'radiology_attachments',
            },
        ),
        migrations.CreateModel(
            name='RadiologyScheduling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('machine', models.CharField(max_length=100)),
                ('priority', models.CharField(
                    choices=[
                        ('Routine', 'Routine'),
                        ('Urgent', 'Urgent'),
                        ('Emergency', 'Emergency'),
                    ],
                    default='Routine',
                    max_length=20,
                )),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='hospitalapp.radiologyorder')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'radiology_schedulings',
            },
        ),
    ]
