# Generated by Django 6.0.3 on 2026-06-04 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0025_create_lis_ris_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Manage Staffs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hospitalapp.user',),
        ),
        migrations.AddField(
            model_name='bill',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.laborder'),
        ),
        migrations.AddField(
            model_name='bill',
            name='radiology_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.radiologyorder'),
        ),
    ]
