# Generated by Django 6.0.3 on 2026-06-08 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0026_staff_bill_lab_order_bill_radiology_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('receptionist', 'receptionist'), ('pharmacist', 'pharmacist'), ('patient', 'patient'), ('nurse', 'nurse'), ('nursing_station', 'Nursing Station'), ('lab_technician', 'Lab Technician'), ('laboratoryist', 'Laboratoryist'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist')], max_length=20),
        ),
        migrations.CreateModel(
            name='NurseAvailability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Emergency Duty', 'Emergency Duty'), ('Off Duty', 'Off Duty')], default='Available', max_length=20)),
                ('current_assignment', models.CharField(blank=True, max_length=255, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'nurse_availability',
            },
        ),
        migrations.CreateModel(
            name='NursingAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nursing_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='NursingMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nursing_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nursing_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nursing_messages',
            },
        ),
        migrations.CreateModel(
            name='NursingNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nursing_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_nursing_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nursing_notifications',
            },
        ),
        migrations.CreateModel(
            name='NursingStationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('Vitals Check', 'Vitals Check'), ('ECG Setup', 'ECG Setup'), ('Blood Collection', 'Blood Collection'), ('Injection', 'Injection'), ('IV Cannulation', 'IV Cannulation'), ('Nebulization', 'Nebulization'), ('Dressing', 'Dressing'), ('Wheelchair Support', 'Wheelchair Support')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('patient_type', models.CharField(choices=[('OP', 'OP'), ('IP', 'IP'), ('ICU', 'ICU'), ('Emergency', 'Emergency')], default='OP', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_requests', to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_requests', to='hospitalapp.patient')),
            ],
            options={
                'db_table': 'nursing_station_requests',
            },
        ),
        migrations.CreateModel(
            name='NursingTaskAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='hospitalapp.nurse')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospitalapp.nursingstationrequest')),
            ],
            options={
                'db_table': 'nursing_task_assignments',
            },
        ),
    ]
