# Generated by Django 6.0.3 on 2026-06-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0027_emergencyalert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='hospitalapp.admission'),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='triggered_by_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nurse'),
        ),
    ]
