# Generated by Django 6.0.3 on 2026-06-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0028_emergencyalert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingstationrequest',
            name='request_type',
            field=models.CharField(choices=[('Vitals Check', 'Vitals Check'), ('ECG Setup', 'ECG Setup'), ('Blood Collection', 'Blood Collection'), ('Injection', 'Injection'), ('IV Cannulation', 'IV Cannulation'), ('Nebulization', 'Nebulization'), ('Dressing', 'Dressing'), ('Wheelchair Support', 'Wheelchair Support'), ('Doctor Support', 'Doctor Support')], max_length=50),
        ),
    ]
