# Generated by Django 6.0.3 on 2026-06-08 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0029_emergencyalert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingstationrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_requests', to='hospitalapp.patient'),
        ),
    ]
