# Generated by Django 6.0.3 on 2026-06-08 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0030_emergencyalert_alert_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('monitor_available', models.BooleanField(default=False)),
                ('ventilator_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emergency_beds',
            },
        ),
        migrations.CreateModel(
            name='EmergencyZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=20)),
                ('priority_level', models.IntegerField()),
                ('target_response_time', models.IntegerField()),
            ],
            options={
                'db_table': 'emergency_zones',
            },
        ),
        migrations.AddField(
            model_name='casuality',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='alert_type',
            field=models.CharField(choices=[('Critical Patient', 'Critical Patient'), ('Code Blue', 'Code Blue'), ('Trauma', 'Trauma'), ('Cardiac Emergency', 'Cardiac Emergency')], default='Critical Patient', max_length=50),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to='hospitalapp.nurse'),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='emergency_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='response_time',
            field=models.IntegerField(blank=True, help_text='Response time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lab_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='urgency',
            field=models.CharField(choices=[('STAT', 'STAT'), ('Urgent', 'Urgent'), ('Routine', 'Routine')], default='Routine', max_length=20),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_radiology_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_radiology_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='urgency',
            field=models.CharField(choices=[('STAT', 'STAT'), ('Urgent', 'Urgent'), ('Routine', 'Routine')], default='Routine', max_length=20),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='clinical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casuality',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Triage Completed', 'Triage Completed'), ('Under Emergency Care', 'Under Emergency Care'), ('In Observation', 'In Observation'), ('Stabilized', 'Stabilized'), ('Referred', 'Referred'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('OT Transfer', 'OT Transfer'), ('ICU Transfer', 'ICU Transfer')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='casuality',
            name='assigned_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_casualties', to='hospitalapp.emergencybed'),
        ),
        migrations.CreateModel(
            name='EmergencyObservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_start', models.DateTimeField(auto_now_add=True)),
                ('observation_end', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('casualty_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='hospitalapp.casuality')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nurse')),
            ],
            options={
                'db_table': 'emergency_observations',
            },
        ),
        migrations.CreateModel(
            name='EmergencyTreatmentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_started', models.DateTimeField(auto_now_add=True)),
                ('treatment_completed', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField()),
                ('treatment_notes', models.TextField()),
                ('casualty_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='hospitalapp.casuality')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
            ],
            options={
                'db_table': 'emergency_treatment_records',
            },
        ),
        migrations.CreateModel(
            name='EmergencyTriage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('triage_time', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField()),
                ('pain_score', models.IntegerField()),
                ('priority_level', models.CharField(max_length=50)),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('oxygen_level', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('sugar_level', models.IntegerField(blank=True, null=True)),
                ('gcs_score', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('casualty_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='hospitalapp.casuality')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
                ('triage_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.nurse')),
                ('triage_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.emergencyzone')),
            ],
            options={
                'db_table': 'emergency_triages',
            },
        ),
        migrations.AddField(
            model_name='casuality',
            name='triage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casualty_link', to='hospitalapp.emergencytriage'),
        ),
        migrations.AddField(
            model_name='emergencybed',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitalapp.emergencyzone'),
        ),
        migrations.AddField(
            model_name='casuality',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casualties', to='hospitalapp.emergencyzone'),
        ),
    ]
