# Generated by Django 6.0.3 on 2026-06-10 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0031_emergencybed_emergencyzone_casuality_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyCounter',
            fields=[
                ('counter_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('General Counter', 'General Counter'), ('Insurance Counter', 'Insurance Counter'), ('Senior Citizen Counter', 'Senior Citizen Counter'), ('Corporate Counter', 'Corporate Counter'), ('Emergency Fast Track Counter', 'Emergency Fast Track Counter')], default='General Counter', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Busy', 'Busy'), ('Closed', 'Closed'), ('Break', 'Break')], default='Closed', max_length=20)),
            ],
            options={
                'db_table': 'pharmacy_counters',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('receptionist', 'receptionist'), ('pharmacist', 'pharmacist'), ('senior_pharmacist', 'Senior Pharmacist'), ('pharmacy_supervisor', 'Pharmacy Supervisor'), ('inventory_manager', 'Inventory Manager'), ('patient', 'patient'), ('nurse', 'nurse'), ('nursing_station', 'Nursing Station'), ('lab_technician', 'Lab Technician'), ('laboratoryist', 'Laboratoryist'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist')], max_length=20),
        ),
        migrations.CreateModel(
            name='PharmacyAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='CounterPerformance',
            fields=[
                ('perf_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_served', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('total_skipped', models.IntegerField(default=0)),
                ('average_serving_time', models.IntegerField(default=0)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.pharmacycounter')),
            ],
            options={
                'db_table': 'counter_performances',
            },
        ),
        migrations.CreateModel(
            name='CounterAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospitalapp.pharmacycounter')),
            ],
            options={
                'db_table': 'counter_assignments',
            },
        ),
        migrations.CreateModel(
            name='PharmacyToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.CharField(max_length=20, unique=True)),
                ('priority_level', models.CharField(choices=[('Regular', 'Regular'), ('Senior Citizen', 'Senior Citizen'), ('Corporate', 'Corporate'), ('VIP', 'VIP'), ('Emergency', 'Emergency')], default='Regular', max_length=30)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Called', 'Called'), ('Processing', 'Processing'), ('Dispensed', 'Dispensed'), ('Completed', 'Completed'), ('Skipped', 'Skipped'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_time', models.IntegerField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.bill')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='hospitalapp.pharmacycounter')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.prescription')),
            ],
            options={
                'db_table': 'pharmacy_tokens',
            },
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_requested', models.IntegerField()),
                ('quantity_dispensed', models.IntegerField()),
                ('status', models.CharField(choices=[('Full', 'Full'), ('Partial', 'Partial'), ('Substituted', 'Substituted'), ('Held', 'Held')], default='Full', max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.medicine')),
                ('substituted_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_dispensings', to='hospitalapp.medicine')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='hospitalapp.pharmacytoken')),
            ],
            options={
                'db_table': 'dispensing_records',
            },
        ),
        migrations.CreateModel(
            name='QueueTransfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('from_counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='hospitalapp.pharmacycounter')),
                ('to_counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='hospitalapp.pharmacycounter')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hospitalapp.pharmacytoken')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_transfers',
            },
        ),
        migrations.CreateModel(
            name='TokenCallLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('recall_count', models.IntegerField(default=0)),
                ('called_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.pharmacycounter')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='hospitalapp.pharmacytoken')),
            ],
            options={
                'db_table': 'token_call_logs',
            },
        ),
        migrations.CreateModel(
            name='VoiceAnnouncementLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_text', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='English', max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('is_played', models.BooleanField(default=False)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.pharmacycounter')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.pharmacytoken')),
            ],
            options={
                'db_table': 'voice_announcement_logs',
            },
        ),
    ]
