# Generated by Django 6.0.3 on 2026-06-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0032_pharmacycounter_alter_user_role_pharmacyauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacytoken',
            name='token_number',
            field=models.CharField(max_length=20),
        ),
    ]
