# Generated by Django 6.0.3 on 2026-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0033_alter_pharmacytoken_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='priority_level',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Senior Citizen', 'Senior Citizen'), ('VIP', 'VIP'), ('Emergency', 'Emergency'), ('Corporate', 'Corporate')], default='Regular', max_length=20),
        ),
    ]
