# Generated by Django 6.0.3 on 2026-06-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0034_prescription_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Senior Citizen', 'Senior Citizen'), ('VIP', 'VIP'), ('Emergency', 'Emergency'), ('Corporate', 'Corporate')], max_length=20, null=True),
        ),
    ]
