# Generated by Django 6.0.3 on 2026-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0035_alter_prescription_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('receptionist', 'receptionist'), ('pharmacist', 'pharmacist'), ('senior_pharmacist', 'Senior Pharmacist'), ('pharmacy_supervisor', 'Pharmacy Supervisor'), ('inventory_manager', 'Inventory Manager'), ('patient', 'patient'), ('nurse', 'nurse'), ('nursing_station', 'Nursing Station'), ('nursing_superintendent', 'Nursing Superintendent'), ('lab_technician', 'Lab Technician'), ('laboratoryist', 'Laboratoryist'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist')], max_length=30),
        ),
    ]
