# Generated by Django 6.0.3 on 2026-06-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0036_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
